##
# This file is part of the IVMS Online.
#
# @copyright 2023 © by Rafał Wrzeszcz - Wrzasq.pl.
##

version: 2
updates:
    -
        package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
