##
# This file is part of the IVMS Online.
#
# @copyright 2023 - 2024 © by Rafał Wrzeszcz - Wrzasq.pl.
##

on:
    workflow_call:

env:
    SCCACHE_GHA_ENABLED: "true"

jobs:
    build:
        runs-on: "ubuntu-22.04"
        container:
            image: "rafalwrzeszczwrzasqpl/build-rust:nightly-v0.2.0"
        services:
            dynamodb:
                image: "amazon/dynamodb-local:2.2.1"
        steps:
            -
                uses: "actions/checkout@v4.1.1"
            -
                uses: "crazy-max/ghaction-github-runtime@v3.0.0"
            -
                run: "make build-dev"
            -
                run: "make test"
                env:
                    AWS_REGION: "${{ vars.AWS_REGION }}"
                    AWS_ACCESS_KEY_ID: "dummy"
                    AWS_SECRET_ACCESS_KEY: "dummy"
                    DYNAMODB_LOCAL_HOST: "http://dynamodb:8000"
            -
                run: "make check"
            -
                run: "make doc"
            -
                run: "make lcov"
            -
                uses: "codecov/codecov-action@v4.0.1"
                with:
                    token: "${{ vars.CODECOV_TOKEN }}"
                    flags: "unittests,rust-${{ vars.RUST_BUILD_TARGET }}"
                    fail_ci_if_error: true
                    verbose: true

    release:
        if: "(github.event_name == 'push') && (github.event.ref == 'refs/heads/master')"
        runs-on: "ubuntu-22.04"
        container:
            image: "rafalwrzeszczwrzasqpl/build-rust:nightly-v0.2.0"
        needs: "build"
        permissions:
            contents: "write"
            id-token: "write"
        steps:
            -
                uses: "actions/checkout@v4.1.1"
            -
                uses: "crazy-max/ghaction-github-runtime@v3.0.0"
            -
                uses: "aws-actions/configure-aws-credentials@v4.0.1"
                with:
                    role-to-assume: "${{ secrets.AWS_IAM_ROLE_ARN }}"
                    aws-region: "${{ vars.AWS_REGION }}"
            -
                run: |
                    git config --global user.name "GitHub Actions"
                    git config --global user.email "office@wrzasq.pl"
                    git config --global --add safe.directory "$GITHUB_WORKSPACE"
            -
                run: "cargo release patch --execute --no-confirm --no-publish --all-features --tag-name 'release-{{version}}' --no-push"
            -
                id: "tag"
                run: "echo version=$(git describe --abbrev=0 | sed s/release-//g) >> $GITHUB_OUTPUT"
            -
                run: "make build"
            -
                run: "make package"
            -
                run: |
                    for file in target/*.zip; do
                        aws s3 cp $file "s3://chilldev-repository/sam/${GITHUB_REPOSITORY}/${{ steps.tag.outputs.version }}/";
                    done

                    echo "{\"version\":\"${{ steps.tag.outputs.version }}\"}" > build-info.json
                    zip --exclude "target/*" --exclude ".git*" -r checkout.zip .
                    aws s3 cp checkout.zip "s3://stackset-organization-global-3616-pipelinesbucket-rjs8r4gs0f1d/${{ github.event.repository.name }}/checkout.zip"
            -
                uses: "ad-m/github-push-action@v0.8.0"
                with:
                    github_token: "${{ secrets.GITHUB_TOKEN }}"
                    branch: "${{ github.ref }}"
